### ISSUE TITLE
About release time

### ISSUE THREAD

**Issue by MRHan-426** [diaodiao317/AICAM#1]
Hi diao,
I‘d like to express my gratitude for your exceptional work. I've been closely following your project, and it has truly ignited a wealth of inspiration within me.

Could you kindly share when the code is expected to be released?

Best regard,
Ziqi

**Comment by diaodiao317** [comment]
I've been quite busy lately, but if our paper gets accepted, I'll make sure to organize the code and model weights as soon as possible and upload them.
